### ISSUE TITLE
Have some issues getting it to run on Mac OSX

### ISSUE THREAD

**Issue by jbobbylopez** [bigpresh/Dancer-Plugin-NYTProf#8]
blopez$ perl bin/app.pl 
Could not find nytprofhtml script.  Ensure it's in your path, or set the nytprofhtml_path option in your config. at /opt/local/lib/perl5/site_perl/5.12.4/Dancer/Plugin/NYTProf.pm line 64.
Compilation failed in require at /App/lib/App.pm line 11.
BEGIN failed--compilation aborted at /App/lib/App.pm line 11.
Compilation failed in require at bin/app.pl line 4.
BEGIN failed--compilation aborted at bin/app.pl line 4.
blopez$ export PATH="$PATH:/opt/local/libexec/perl5.12/sitebin/"
blopez$ perl bin/app.pl 
Segmentation fault: 11
blopez$ 

I tried using placing the nytprofhtml configuration in config.yml according the instructions on the github wiki, but that didn't do anything (didn't work, and no warnings/errors).

Let me know if there's anything else I can check to help out.

Directory structure for stuff NYTProf related:
/opt/local/lib/perl5/site_perl/5.12.4/Dancer/Plugin/NYTProf.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/auto/Dancer/Plugin/NYTProf
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/auto/Dancer/Plugin/NYTProf/.packlist
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/auto/Devel/NYTProf
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/auto/Devel/NYTProf/.packlist
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/auto/Devel/NYTProf/NYTProf.bs
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/auto/Devel/NYTProf/NYTProf.bundle
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/auto/Devel/NYTProf
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/auto/Devel/NYTProf/NYTProf.bundle
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Apache.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Constants.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Core.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Data.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/FileHandle.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/FileInfo.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/asc.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/bg.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/desc.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/gradient-cushion1.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/gradient.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/gradient20.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/gradient30.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/gradient40.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/gradient50.png
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/jit-yc.js
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/jit.js
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jit/Treemap.css
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jquery-min.js
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/jquery-tablesorter-min.js
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/js/style-tablesorter.css
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Reader.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/ReadStream.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Run.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/SubInfo.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Test.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf/Util.pm
/opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm
/opt/local/libexec/perl5.12/sitebin/nytprofcg
/opt/local/libexec/perl5.12/sitebin/nytprofcsv
/opt/local/libexec/perl5.12/sitebin/nytprofhtml
/opt/local/libexec/perl5.12/sitebin/nytprofmerge
/opt/local/share/perl5.12/siteman/man1/nytprofcg.1
/opt/local/share/perl5.12/siteman/man1/nytprofcsv.1
/opt/local/share/perl5.12/siteman/man1/nytprofhtml.1
/opt/local/share/perl5.12/siteman/man1/nytprofmerge.1
/opt/local/share/perl5.12/siteman/man3/Dancer::Plugin::NYTProf.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf::Apache.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf::Core.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf::Data.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf::FileInfo.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf::ReadStream.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf::Run.3pm
/opt/local/share/perl5.12/siteman/man3/Devel::NYTProf::Util.3pm

**Comment by jbobbylopez** [comment]
More info:

Hardware Overview:

  Model Name:   MacBook Pro
  Model Identifier: MacBookPro8,2
  Processor Name:   Intel Core i7
  Processor Speed:  2.4 GHz

> > Dancer 1.31 server 1462 listening on http://0.0.0.0:8080
> > Dancer::Plugin::NYTProf (0.21)

Test Script:

```
    #!/usr/bin/perl 

    use strict;
    use warnings;

    use Dancer ':syntax';
    use FindBin;
    use Cwd qw/realpath/;    # For use by $appdir
    use Dancer::Plugin::NYTProf;
    use Data::Dumper;
    set port => 8080;

    #__[[ SETUP ] ] ______________________________________________________________

    my ( $self_bin, $self_real_bin, $self ) = 
    (
          $FindBin::Bin,    # Seeming location of the script
          $FindBin::RealBin,            # Real location of the script
          $FindBin::RealScript          # Actual name of the script
    );

    my $appdir = realpath("$FindBin::Bin/..");
    Dancer::Config::setting( 'appdir', $appdir );
    Dancer::Config::load();

    #__[[ ROUTES ] ] ______________________________________________________________ get
    get '/home' => sub {
          info "/home accessed.";

          return 'home';
    };
    dance;
```

Results (after visiting url in browser twice)

```
 >> Dancer 1.31 server 1532 listening on http://0.0.0.0:8080
 >> Dancer::Plugin::NYTProf (0.21)
 == Entering the development dance floor ...
 Use of uninitialized value $_[0] in join or string at /opt/local/lib/perl5/vendor_perl/5.12.4/darwin-thread-multi-2level/File/Spec/Unix.pm line 86.
 Use of uninitialized value $_[0] in join or string at /opt/local/lib/perl5/vendor_perl/5.12.4/darwin-thread-multi-2level/File/Spec/Unix.pm line 86.
```

File/Spec/Unix: 86:

```
  73 =item catdir()
  74 
  75 Concatenate two or more directory names to form a complete path ending
  76 with a directory. But remove the trailing slash from the resulting
  77 string, because it doesn't look good, isn't necessary and confuses
  78 OS2. Of course, if this is the root directory, don't cut off the
  79 trailing slash :-)
  80 
  81 =cut
  82 
  83 sub catdir {
  84     my $self = shift;
  85 
  86     $self->canonpath(join('/', @_, '')); # '' because need a trailing '/'
  87 }
```

perl -d:

```
 blopez$ perl -d /tmp/dancer-nytprof.pl 

 Loading DB routines from perl5db.pl version 1.33
 Editor support available.

 Enter h or `h h' for help, or `man perldebug' for more help.

 Subroutine sub redefined at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41, <DATA> line 998.
  at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41, <DATA> line 998.
         require Devel/NYTProf.pm called at /opt/local/lib/perl5/site_perl/5.12.4/Dancer/Plugin/NYTProf.pm line 82
         require Dancer/Plugin/NYTProf.pm called at /tmp/dancer-nytprof.pl line 9
         main::BEGIN() called at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41
         eval {...} called at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41
 DB::sub called unexpectedly at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41, <DATA> line 998.
 Compilation failed in require at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 28, <DATA> line 998.
 Compilation failed in require at /opt/local/lib/perl5/site_perl/5.12.4/Dancer/Plugin/NYTProf.pm line 82, <DATA> line 998.
 Compilation failed in require at /tmp/dancer-nytprof.pl line 9, <DATA> line 998.
 BEGIN failed--compilation aborted at /tmp/dancer-nytprof.pl line 9, <DATA> line 998.
 Debugged program terminated.  Use q to quit or R to restart,
   use o inhibit_exit to avoid stopping after program termination,
   h q, h R or h o to get additional info.  
   DB<1> 
```

**Comment by bigpresh** [comment]
> I tried using placing the nytprofhtml configuration in config.yml according the instructions on the github wiki, but that didn't do anything (didn't work, and no warnings/errors).

Ahhh.  I've just looked at the logic used to handle the `nytprofhtml_path` option, and it appears broken.

The code which works out the path is:

``` perl
my $nytprofhtml_path = File::Which::which(
    $setting->{nytprofhtml_path} || 'nytprofhtml'
)
```

Testing in a debugger:

```
  DB<2> x File::Which::which('nytprofhtml');
0  '/usr/local/bin/nytprofhtml'
  DB<3> x File::Which::which('/usr/local/bin/nytprofhtml');
  empty array
```

So, it appears the fix will be to change it to:

``` perl
my $nytprofhtml_path = $setting->{nytprofhtml_path}
    || File::Which::which('nytprofhtml');
```

**Comment by bigpresh** [comment]
I've just pushed a fix in bdb413b - could you confirm if that fix works for you?  If so, I'll get a new release pushed to CPAN ASAP.

Thanks for providing so much detail in this bug report, by the way - it's great to receive a report with plenty of details!

**Comment by bigpresh** [comment]
Version 0.22 pushed to CPAN just now with this fix; I believe that should sort it for you!

**Comment by jbobbylopez** [comment]
Thanks! Sorry couldn't get to testing it for you sooner, but the fix looks fairly straight-forward.  Will pull from CPAN as soon as it's available on my local mirrors.

**Comment by jbobbylopez** [comment]
So it looks like the code change for nytprofhtml works fine, thanks for that.

I'm still seeing the compilation errors with 'perl -d' though:

```
blopez$ perl -d /tmp/dancer-nytprof.pl 

Loading DB routines from perl5db.pl version 1.33
Editor support available.

Enter h or `h h' for help, or `man perldebug' for more help.

Subroutine sub redefined at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41, <DATA> line 998.
 at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41, <DATA> line 998.
    require Devel/NYTProf.pm called at /opt/local/lib/perl5/site_perl/5.12.4/Dancer/Plugin/NYTProf.pm line 82
    require Dancer/Plugin/NYTProf.pm called at /tmp/dancer-nytprof.pl line 9
    main::BEGIN() called at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41
    eval {...} called at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41
DB::sub called unexpectedly at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 41, <DATA> line 998.
Compilation failed in require at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 28, <DATA> line 998.
Compilation failed in require at /opt/local/lib/perl5/site_perl/5.12.4/Dancer/Plugin/NYTProf.pm line 82, <DATA> line 998.
Compilation failed in require at /tmp/dancer-nytprof.pl line 9, <DATA> line 998.
BEGIN failed--compilation aborted at /tmp/dancer-nytprof.pl line 9, <DATA> line 998.
Debugged program terminated.  Use q to quit or R to restart,
  use o inhibit_exit to avoid stopping after program termination,
  h q, h R or h o to get additional info.  
  DB<1> ^C

blopez$ perl -MDevel::NYTProf -e 'print "bleh"'
blopez$ perl -MDevel::NYTProf::Core -e 'print "bleh"'
```

Compilation failed in require at /opt/local/lib/perl5/site_perl/5.12.4/darwin-thread-multi-2level/Devel/NYTProf.pm line 28

```
  19 # Enable specific perl debugger flags (others may be set later).
  20 # Set the flags that influence compilation ASAP so we get full details
  21 # (sub line ranges etc) of modules loaded as a side effect of loading
  22 # Devel::NYTProf::Core (ie XSLoader, strict, Exporter etc.)
  23 # See "perldoc perlvar" for details of the $^P ($PERLDB) flags
  24 $^P = 0x010     # record line range of sub definition
  25     | 0x100     # informative "file" names for evals
  26     | 0x200;    # informative names for anonymous subroutines
  27 
  28 require Devel::NYTProf::Core;    # loads XS and sets options
  29 
  30 # XXX hack, need better option handling e.g., add DB::get_option('use_db_sub')
  31 my $use_db_sub = ($ENV{NYTPROF} && $ENV{NYTPROF} =~ m/\buse_db_sub=1\b/);
  32 if ($use_db_sub) {                     # install DB::DB sub
  33     *DB = ($] < 5.008008)
  34         ? sub { goto &DB_profiler }    # workaround bug in old perl versions (slow)
  35         : \&DB_profiler;
  36 }
```

Compilation failed in require at /opt/local/lib/perl5/site_perl/5.12.4/Dancer/Plugin/NYTProf.pm line 82

```
70 # Need to load Devel::NYTProf at runtime after setting env var, as it will
71 # insist on creating an nytprof.out file immediately - even if we tell it not to
72 # start profiling.
73 # Dirty workaround: get a temp file, then let Devel::NYTProf use that, with
74 # addpid enabled so that it will append the PID too (so the filename won't
75 # exist), load Devel::NYTProf, then unlink the file.
76 # This is dirty, hacky shit that needs to die, but should make things work for
77 # now.
78 my $tempfh = File::Temp->new;
79 my $file = $tempfh->filename;
80 $tempfh = undef; # let the file get deleted
81 $ENV{NYTPROF} = "start=no:file=$file";
82 require Devel::NYTProf;
83 unlink $file;
```

**Comment by bigpresh** [comment]
Interesting, I'm puzzled by this one.  It sounds to me like Devel::NYTProf is getting loaded multiple times, but that shouldn't be the case as far as I can see.  Hmm.

**Comment by bigpresh** [comment]
(As you can see it's loaded at runtime after creating a temp file and setting an env var, but it's using `require` - if it tries to `require` it again on subsequent hits it should be a no-op.)

Just to confirm, your test script is still the same as the one in your original report, yes?

**Comment by bigpresh** [comment]
Having thought this through more, I think it's simply an interaction between the normal perl debugger `perl5db.pl` and `Devel::NYTProf` (which is another debugger interface in effect, hence it would be used from the commandline as `perl -d:NYTProf ...`).

I don't think this is an issue specific to Dancer::Plugin::DevelNYTProf, or one that I can solve.
